name: Build Ruby 2.4.3 for Termux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential git curl libssl-dev libreadline-dev zlib1g-dev libffi-dev autoconf bison libgdbm-dev libncurses5-dev libyaml-dev

      - name: Download Ruby 2.4.3
        run: |
          curl -O https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.3.tar.gz
          tar -xzf ruby-2.4.3.tar.gz
          cd ruby-2.4.3
          ./configure --prefix=/usr/local/ruby243 --disable-install-doc
          make -j$(nproc)
          make install

      - name: Create .deb package structure
        run: |
          mkdir -p ruby243_deb/usr/local
          cp -r /usr/local/ruby243 ruby243_deb/usr/local/
          mkdir -p ruby243_deb/DEBIAN
          cat <<EOF > ruby243_deb/DEBIAN/control
          Package: ruby243
          Version: 2.4.3
          Section: interpreters
          Priority: optional
          Architecture: armhf
          Maintainer: YourName <you@example.com>
          Description: Ruby 2.4.3 built for Termux (armv8l/armhf)
          EOF

      - name: Build .deb
        run: |
          dpkg-deb --build ruby243_deb

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v3
        with:
          name: ruby243-termux
          path: ruby243_deb.deb
